BOOTLOADER_SIZE = 6144

# defaul
BOOTMAGIC_ENABLE = yes # DO NOT REMOVE
NKRO_ENABLE ?= yes
LTO_ENABLE = yes
EXTRAKEY_ENABLE = yes
LTO_ENABLE = yes
REPEAT_KEY_ENABLE = no
UNICODE_ENABLE = no
UNICODEMAP_ENABLE = no
UCIS_ENABLE = no
UNICODE_COMMON = no
AUTOCORRECT_ENABLE ?= no
CAPS_WORD_ENABLE ?= no
CONSOLE_ENABLE ?= no
GRAVE_ESC_ENABLE ?= no
SPACE_CADET_ENABLE ?= no
TAP_DANCE_ENABLE ?= yes


SELECT_WORD_ENABLE ?= no
ifeq ($(strip $(SELECT_WORD_ENABLE)), yes)
	OPT_DEFS += -DSELECT_WORD_ENABLE
	SRC += features/select_word.c
endif

# KEYCODE_STRING_ENABLE ?= no
# ifeq ($(strip $(KEYCODE_STRING_ENABLE)), yes)
# 	OPT_DEFS += -DKEYCODE_STRING_ENABLE
# 	SRC += features/keycode_string.c
# endif
